title: Tom Renn
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://tomrenn.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about

social:
   github: tomrenn
   twitter: tomrenn
   email: tom.renn@dowjones.com

google_analytics: "UA-68092526-1"
